name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Using a recent, stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get version from file
        id: version
        run: echo "app_version=$(cat VERSION.txt)" >> $env:GITHUB_OUTPUT

      - name: Package application
        run: flet pack main.py --name UniversalConverter --product-name "Universal Converter" --product-version ${{ steps.version.outputs.app_version }}
        env:
          PYTHONUTF8: "1"

      - name: Zip the output
        run: |
          Compress-Archive -Path dist/UniversalConverter.exe -DestinationPath dist/UniversalConverter-v${{ steps.version.outputs.app_version }}.zip

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.app_version }}
          body: "New release of Universal Converter."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
