name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Using a recent, stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get version from file
        id: version
        run: echo "app_version=$(cat VERSION.txt)" >> $env:GITHUB_OUTPUT

      - name: Package application
        run: flet build windows --project UniversalConverter --product "Universal Converter" --build-version ${{ steps.version.outputs.app_version }} --no-rich-output
        env:
          PYTHONUTF8: "1"

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/dist/UniversalConverter.msix
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.app_version }}
          body: "New release of Universal Converter."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
