name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and Extract FFmpeg
        run: |
          curl -L -o ffmpeg.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
          7z x ffmpeg.7z -offmpeg
          Move-Item -Path ffmpeg/ffmpeg-*/bin/* -Destination ./ffmpeg-bin
        shell: pwsh

      - name: Get version from file
        id: version
        run: echo "app_version=$(cat VERSION.txt)" >> $env:GITHUB_OUTPUT

      - name: Package application with PyInstaller
        run: |
          pyinstaller main_pyside.py `
            --name UniversalConverter `
            --noconsole `
            --onedir `
            --add-data "ffmpeg-bin;ffmpeg-bin"
        shell: pwsh
        env:
          PYTHONUTF8: "1"

      - name: Zip the output
        run: |
          Compress-Archive -Path dist/UniversalConverter/* -DestinationPath dist/UniversalConverter-v${{ steps.version.outputs.app_version }}.zip

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.app_version }}
          body: "New release of Universal Converter."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
